inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  SuggestExtensions: true
  EnabledByDefault: true
  TargetRubyVersion: 3.2.2

Style/Copyright:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Layout/RedundantLineBreak:
  Enabled: false
